// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pkypuxllmyotsruumlkt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBreXB1eGxsbXlvdHNydXVtbGt0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgyODk2ODksImV4cCI6MjA3Mzg2NTY4OX0.A2ewncEfUQmiR5SuTYdniR26eZmILztPBlBgmzQEaKI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});